window.modLangs = JSON.stringify({
    en: {
        home: "Home",
        macros: "Macros",
        game: "Game",
        name: "Name",
        themes: "Themes",
        fps: "FPS",
        languages: "Languages",
        Autor: "Autor",

        home: {
            stats: "ㆍYour stats",
            time:"Time Played",
            maxmass:"Max Mass",
            deaths:"Total deaths",
            totalmass:"Total Mass",
            beta:"ㆍPlay the BETA version",
            quick:"ㆍQuick access",
            profile:"ㆍMod profile",
            notes:"Notes or description",
         },
         macros: {
            keybindings:"Keybindings",
            rapidfeed:"Rapid Feed",
            doublesplit:"Double Split",
            triplesplit:"Triple split",
            quadsplit:"Quad Split",
            freezeplayer:"Freeze Player",
            verticalline:"Vertical Line",
            togglemenu:"Toggle Menu",
            advancedkey:"Advanced Keybinding Options",
            mousemacros:"Feed or Split with mouse buttons",
            freezep:"Freeze your player on the Map and linesplit",
            typefreeze:"Type of Freeze",
            togglegen:"Toggle Settings",
            toggleset:"Toggle settings with a keybind",
            togglenames:"Toggle Names",
            toggleskins:"Toggle Skins",
            toggleskins:"Toggle Autorespawn",
            tricksplits:"Tricksplits",
            tricksdes:"Other split options",
            doubletrick:"Double Trick",
            selftrick:"Self Trick",
         },
         game: {
            mapcol: "Map Color",
            bordercol:"Border Colors",
            foodcol:"Food Color",
            cellcol:"Cell Color",
            virusimg:"Virus Image",
            replaceskn:"Replace Skins",
            deathpos:"Death screen Position",
            timer:"Play timer",
         },
         name: {
            nfonts: "Name fonts & special characters",
            namedes:"Customize your name with special characters or fonts",
            savenames:"Save names",
            nsavedes:"Save your names local",
            namecol:"Name Color",
            namecoldes:"Customize your name color",
            gradientname:"Gradient Name",
            gradientndes:"Customize your name with a gradient color",
            firstcol:"First Color",
            secondcol:"Second Color",
         },
         themes: {
            create: "Create",
         },
         fps: {
            modefps: "FPS Mode [Beta]",
            configfps: "Custom FPS Settings",
            hidefood: "Hide Food",
            shownam: "Show Names",
            shortenlongna: "Shorten long names",
            rtextshadow: "Remove text shadows",
         },
         Autor: {
            privacy: "Privacy and Security notice / GitHub",
         },
    },
    es: {
        home: "Inicio",
        macros: "Macros",
        game: "Juego",
        name: "Nombre",
        themes: "Temas",
        fps: "FPS",
        languages: "Idiomas",
        Autor: "Autor",

        home: {
            stats: "ㆍTus estadísticas",
            time:"Tiempo total",
            maxmass:"Masa Max.",
            deaths:"Tus muertes",
            totalmass:"Masa Total",
            beta:"ㆍJuega la versión BETA",
            quick:"ㆍAcceso rapido",
            profile:"ㆍPerfil del Mod",
            notes:"Descripción general",
         },
         macros: {
            keybindings:"Atajos de teclado",
            rapidfeed:"Masa Rápida",
            doublesplit:"División Doble",
            triplesplit:"División Triple",
            quadsplit:"4 Divisiones",
            freezeplayer:"Congelamiento",
            verticalline:"Linea Vertical",
            togglemenu:"Mostrar menú",
            advancedkey:"Opciones avanzadas de atajos",
            mousemacros:"Alimentar o dividir con los botones del mouse",
            freezep:"Congelación en el mapa y líneas divididas",
            typefreeze:"Tipo de congelación",
            bindset:"Efectuar comando con",
            togglegen:"Alternar configuración",
            toggleset:"Alternar configuración con atajos",
            togglenames:"Alternar nombres",
            toggleskins:"Alternar Skins",
            toggleskins:"Alternar Autorespawn",
            tricksplits:"Tricksplits",
            tricksdes:"Otras opciones de división",
            doubletrick:"Double Trick",
            selftrick:"Auto Trick",
         },
         game: {
            mapcol: "Color del mapa",
            bordercol:"Color de borde",
            foodcol:"Color de alimento",
            cellcol:"Color de celda",
            virusimg:"Imagen de virus",
            replaceskn:"Reemplazar máscaras",
            deathpos:"Mostrar pantalla de muerte",
            timer:"Mostrar temporizador",
         },
         name: {
            nfonts: "Tipografías y caracteres especiales.",
            namedes:"Personaliza tu nombre con caracteres o tipografías.",
            savenames:"Guardar nombres",
            nsavedes:"Guardar nombres locales",
            namecol:"Color de nombre",
            namecoldes:"Personalizar color",
            gradientname:"Nombre gradiente",
            gradientndes:"Personalizar colores",
            firstcol:"1er color",
            secondcol:"2do color",
         },
         themes: {
            create: "Crear",
         },
         fps: {
            modefps: "Modo FPS [Beta]",
            configfps: "Configuraciones FPS",
            hidefood: "Mostrar alimento",
            shownam: "Mostrar nombres",
            shortenlongna: "Cortar nombres largos",
            rtextshadow: "Remover sombra de nombres",
         },
         Autor: {
            privacy: "Aviso de Privacidad y Seguridad / GitHub",
         },
    },
    ru: {
      home: "Обзор",
      macros: "Макрос",
      game: "Игра",
      name: "Имя",
      themes: "Тема",
      fps: "FPS",
      languages: "Язык",
      Autor: "Автор",

      home: {
          stats: "ㆍСтатистика",
          time:"Всего",
          maxmass:"Рекорд",
          deaths:"Кол-во смертей",
          totalmass:"Общая масса",
          beta:"ㆍИграй в БЕТА-версию",
          quick:"ㆍНастройки",
          profile:"ㆍПрофиль",
          notes:"Описание",
       },
       macros: {
          keybindings:"Горячие клавиши",
          rapidfeed:"Кормление",
          doublesplit:"Двойное разделение",
          triplesplit:"Тройное разделение",
          quadsplit:"Четверное разделение",
          freezeplayer:"Остановиться",
          verticalline:"Вертикальная линия",
          togglemenu:"Навигация",
          advancedkey:"Дополнительные параметры",
          mousemacros:"Кормить или разделиться с помощью мыши",
          freezep:"Остановите своего игрока",
          typefreeze:"Способ остановки",
          togglegen:"Настройки навигации",
          toggleset:"Настройки навигации с помощью клавиш",
          togglenames:"Имена",
          toggleskins:"Скины",
          toggleskins:"Автовозрождение",
          tricksplits:"Трюки",
          tricksdes:"Другие варианты разделения",
          doubletrick:"Double Трюк",
          selftrick:"Self Трюк",
       },
       game: {
          mapcol: "Цвет карты",
          bordercol:"Цвет границ",
          foodcol:"Цвет еды",
          cellcol:"Цвет Клетки",
          virusimg:"Изображение вируса",
          replaceskn:"Заменить скин",
          deathpos:"положение экрана после смерти",
          timer:"Игровой таймер",
       },
       name: {
          nfonts: "Шрифты и специальные символы",
          namedes:"Настройте имя с помощью символов или шрифтов",
          savenames:"Сохраненные имена",
          nsavedes:"Сохраните ваше имя",
          namecol:"Цвет имени",
          namecoldes:"Настройте цвет имени",
          gradientname:"Градиентное имя ",
          gradientndes:"Настройте имя с помощью градиентного цвета",
          firstcol:"Первый цвет",
          secondcol:"Второй цвет",
       },
       themes: {
          create: "Создать",
       },
       fps: {
          modefps: "FPS Мод [Бета]",
          configfps: "Собственные FPS Настройки",
          hidefood: "Скрыть еду",
          shownam: "Показать имена",
          shortenlongna: "Сократить длинные имена",
          rtextshadow: "Убрать тени текста",
       },
       Autor: {
          privacy: "Уведомление о конфиденциальности и безопасности / GitHub",
       },
  },
  })